// Auto-generated by packages/providers/scripts/update-current-gen.ts
// Last updated: 2026-01-19T01:14:25.970Z

import type { ModelId } from "./model"

/**
 * Current generation model IDs per provider.
 * These are the latest/flagship models that should be shown by default.
 */
export const CURRENT_GEN_MODEL_IDS: readonly ModelId[] = [
  "anthropic/claude-opus-4-5-20251101" as ModelId,
  "anthropic/claude-sonnet-4-5-20250929" as ModelId,
  "anthropic/claude-haiku-4-5-20251001" as ModelId,
  "bedrock/anthropic.claude-opus-4-5-20251101-v1:0" as ModelId,
  "bedrock/anthropic.claude-sonnet-4-5-20250929-v1:0" as ModelId,
  "bedrock/anthropic.claude-haiku-4-5-20251001-v1:0" as ModelId,
  "openai/gpt-5.2-chat-latest" as ModelId,
  "openai/gpt-5.2-pro" as ModelId,
  "openai/gpt-5.2-codex" as ModelId,
  "google/gemini-3-flash-preview" as ModelId,
  "google/gemini-3-pro-preview" as ModelId,
  "mistral/mistral-large-2512" as ModelId,
  "mistral/devstral-2512" as ModelId,
  "mistral/codestral-latest" as ModelId,
]
